/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.php",
    "./inc/**/*.php",
    "./templates/**/*.html",
    "./parts/**/*.html",
    "./blocks/**/*.php",
    "./js/**/*.js",
    "./stich/**/*.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#11131a",
        "on-tertiary-fixed-variant": "#92001c",
        "on-primary-fixed": "#331200",
        "error": "#ffb4ab",
        "surface-container-high": "#282a31",
        "surface-container-highest": "#33343c",
        "on-primary-fixed-variant": "#763300",
        "primary": "#ffb68d",
        "on-secondary": "#462a00",
        "inverse-primary": "#9b4600",
        "error-container": "#93000a",
        "on-primary-container": "#5b2600",
        "on-tertiary-container": "#730014",
        "on-secondary-fixed-variant": "#653e00",
        "tertiary-fixed": "#ffdad8",
        "on-secondary-container": "#684100",
        "secondary-fixed": "#ffddb7",
        "outline": "#a78b7c",
        "surface-container-lowest": "#0c0e15",
        "tertiary-container": "#ff7273",
        "on-tertiary-fixed": "#410007",
        "surface-dim": "#11131a",
        "on-secondary-fixed": "#2a1700",
        "inverse-on-surface": "#2e3038",
        "surface-variant": "#33343c",
        "on-surface-variant": "#e0c0b0",
        "inverse-surface": "#e2e2ec",
        "on-error-container": "#ffdad6",
        "surface-tint": "#ffb68d",
        "primary-fixed": "#ffdbc9",
        "surface-container-low": "#191b22",
        "secondary": "#ffcb8d",
        "on-surface": "#e2e2ec",
        "secondary-container": "#ffa504",
        "background": "#11131a",
        "primary-container": "#ff7700",
        "tertiary-fixed-dim": "#ffb3b1",
        "tertiary": "#ffb3b1",
        "primary-fixed-dim": "#ffb68d",
        "on-tertiary": "#680011",
        "surface-container": "#1d1f27",
        "on-primary": "#532200",
        "on-error": "#690005",
        "outline-variant": "#584235",
        "on-background": "#e2e2ec",
        "surface-bright": "#373941",
        "secondary-fixed-dim": "#ffb95c"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "gutter-desktop": "2rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "space-2xl": "3rem",
        "space-2xs": "0.25rem",
        "container-max": "1280px",
        "space-md": "1rem",
        "space-3xl": "4rem"
      },
      fontFamily: {
        "headline-xl-mobile": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "body-lg": ["Inter"],
        "headline-sm": ["Montserrat"],
        "label-action": ["Montserrat"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Montserrat"],
        "headline-xl": ["Montserrat"],
        "body-sm": ["Inter"],
        "label-badge": ["Montserrat"],
        "headline-md": ["Montserrat"]
      },
      fontSize: {
        "headline-xl-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "0.02em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "0.04em", "fontWeight": "800" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-action": ["13px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "0.02em", "fontWeight": "800" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "0.03em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-badge": ["11px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "800" }],
        "headline-md": ["22px", { "lineHeight": "28px", "letterSpacing": "0.02em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}


